# Generated by Django 5.2.6 on 2025-09-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="profile_picture",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
