# Generated by Django 5.2.6 on 2025-09-28 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recruiter",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="recruiter",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("company", models.CharField(blank=True, max_length=255)),
                ("position", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
