# Generated by Django 5.2.6 on 2025-09-26 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recruiter",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="recruiter",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("company", models.CharField(blank=True, max_length=255)),
                ("position", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "summary",
                    models.TextField(help_text="Short role summary.", max_length=2000),
                ),
                (
                    "responsibilities",
                    models.TextField(
                        blank=True, help_text="List responsibilities (one per line)."
                    ),
                ),
                (
                    "salary",
                    models.CharField(
                        blank=True,
                        help_text="Example: $80k–$100k or $45/hr",
                        max_length=100,
                    ),
                ),
                (
                    "work_hours",
                    models.CharField(
                        blank=True,
                        help_text="Example: Full-time, 40hrs/wk, M–F",
                        max_length=100,
                    ),
                ),
                (
                    "skills_required",
                    models.TextField(
                        blank=True, help_text="List skills (comma- or line-separated)."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_postings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
