# Generated by Django 5.2.6 on 2025-09-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="remote",
            field=models.BooleanField(default=False, help_text="Is this job remote?"),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="visa_sponsorship",
            field=models.BooleanField(
                default=False, help_text="Visa sponsorship available?"
            ),
        ),
    ]
