# Generated by Django 5.2.6 on 2025-09-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Application",
        ),
    ]
