# Generated by Django 5.2.6 on 2025-09-21 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="applicant",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("college", models.CharField(max_length=255)),
                ("graduation_year", models.DateField()),
                ("degree", models.CharField(blank=True, max_length=200)),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("resume", models.CharField(max_length=255)),
            ],
        ),
    ]
