# Generated by Django 5.2.6 on 2025-09-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="resume",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
